import { Database } from './database.types'

/**
 * Status of a content idea
 * @param saved - Initial state when an idea is created
 * @param in_progress - Idea is being worked on
 * @param completed - Idea has been turned into content
 * @param archived - Idea is no longer active but kept for reference
 */
export type IdeaStatus = 'saved' | 'in_progress' | 'completed' | 'archived'

/**
 * Source of a content idea
 * @param ai_generated - Generated by AI tools
 * @param user_created - Manually created by user
 * @param imported - Imported from external source
 */
export type IdeaSource = 'ai_generated' | 'user_created' | 'imported'

/**
 * Type of content idea
 * @param video_idea - Full video concept
 * @param script_outline - Written content/script
 * @param series_idea - Multi-part content series
 * @param collaboration_idea - Content involving multiple creators
 * @param tutorial_idea - Educational/how-to content
 */
export type IdeaType = 'video_idea' | 'script_outline' | 'series_idea' | 'collaboration_idea' | 'tutorial_idea'

/**
 * Performance and potential metrics for a content idea
 */
export interface IdeaMetrics {
  /** Predicted view count range */
  estimatedViews?: string
  /** Expected engagement rate */
  engagement?: string
  /** Production complexity level */
  difficulty?: string
  /** Estimated production duration */
  timeToCreate?: string
  /** Target demographic information */
  targetAudience?: string
  /** SEO and discovery keywords */
  keywords?: string[]
}

/**
 * Additional metadata and planning information for a content idea
 */
export interface IdeaMetadata {
  scriptOutline?: string[]
  researchNotes?: string
  references?: string[]
  requiredResources?: string[]
  prerequisites?: string[]
  timeline?: {
    research?: string
    scripting?: string
    filming?: string
    editing?: string
    thumbnailCreation?: string
  }
  targetRelease?: string
  estimatedBudget?: string
  collaborators?: string[]
  tags?: string[]
}

/**
 * Complete content idea record with all metadata and tracking fields
 */
export interface ContentIdea {
  /** Unique identifier for the idea */
  id: string
  /** User who owns this idea */
  user_id: string
  /** Main title of the content idea */
  title: string
  /** Detailed description of the content */
  description: string
  /** Type of content (video, series, etc) */
  type: IdeaType
  /** Current status in production pipeline */
  status: IdeaStatus
  /** Performance and potential metrics */
  metrics: IdeaMetrics
  /** Additional planning information */
  metadata: IdeaMetadata
  /** Origin of the idea */
  source: IdeaSource
  /** Creation timestamp */
  created_at: string
  /** Last update timestamp */
  updated_at: string
}

/**
 * Type for creating a new idea, omitting system-managed fields
 */
export type NewContentIdea = Omit<ContentIdea, 'id' | 'user_id' | 'created_at' | 'updated_at'>

// Extract the content_ideas table type from the database
export type DBContentIdea = Database['public']['Tables']['content_ideas']['Row']